### ISSUE TITLE
Memory size is too large in TizenRT

### ISSUE THREAD

**Issue by hs0225** [Samsung/js-remote-test#44]
Look at the memory size of test_buffer.js,

| Board  | Memory Size | 
| :------------ | :-----------: | 
|  STM32 | 32840 Byte | 
| RP2  | 33159 Byte  | 
| Artik053  | 4253768376 Byte  | 

The memory size is abnormally large only in Artik053. We should measure it correctly.

**Comment by yichoi** [comment]
I would like to have proper measurement tool for memory usage dynamically

**Comment by rtakacs** [comment]
@hs0225: Could you please print the value of the stdout variable [here](https://github.com/Samsung/js-remote-test/blob/master/API/device/artik053.py#L112)?

**Comment by hs0225** [comment]
@rtakacs You can see the result [here](https://github.com/hs0225/iotjstest/blob/master/test_result_artik053_171023.txt).

**Comment by zherczeg** [comment]
It seems only the allocated and peak allocated values are wrong. The rest of the allocations are 0 (I suppose this is printed at the end after everything is freed), and peak values are reasonable.

As far as I remember we use a hack to inject external allocation data into JerryScript memstats. Perhaps the injected data is wrong, and that is what @LaszloLango is talking about. Furthermore it seems to me that the injected numbers are kind of random, because there are big, but not too big numbers (e.g. 2813060968) are there.

**Comment by zherczeg** [comment]
@hs0225 does Tizen uses the allocator of nuttix or something else? Is it configured to use 4 or 2 byte sizes?

**Comment by rtakacs** [comment]
@zherczeg As I checked, TizenRT uses the same allocator than NuttX, but it extends the allocnode structure with other debug heap information. That is why the size is 16 bytes.  #46 is a fix for this issue.
