### ISSUE TITLE
Revise measurement tool for dynamic memory usage

### ISSUE THREAD

**Issue by glistening** [Samsung/js-remote-test#45]
This issue is created by https://github.com/Samsung/js-remote-test/issues/44#issuecomment-338562068.
I would like to talk in this issue for efficient and clear communication.

**Comment by rtakacs** [comment]
The main problem with the low footprint devices (like stm32f4dis or artik053) is that there are no professional tools for measuring the memory consumption, especially if the application uses custom allocator.  

Since JerryScript has already a memory monitoring feature (`jerry-memstat`), the easiest way is to use that one. But this feature is only for JerryScript (and for its own allocator), so it is not enough just enable that feature in IoT.js build.

Since IoT.js and libtuv use system allocator, these information can't be calculated into the memory usage by default. To measure the full IoT.js memory consumption, there are 3 patches in [this folder](https://github.com/Samsung/js-remote-test/tree/master/patches) (iotjs-memstat.diff, libtuv-memstat.diff, jerry-memstat.diff) that can help to use the JerryScript's `jmem_heap_stat_alloc` and `jmem_heap_stat_free` statistic functions in IoT.js and libtuv.

This works for NuttX, but it needs some investigation in case of TizenRT.

**Comment by zherczeg** [comment]
@rtakacs described the problem well. Memory tracking requires system hooks, and they are not really provided by low-end OS-es because of low system resources.

What we can do is checking the memory allocator of the OS, and create a hack which reads the block size from a memory pointer when free() is called.

**Comment by glistening** [comment]
@zherczeg, @LaszloLango Could you share current progress on this issue? Please push the PR for updating the daily report based on the decision from last week and this Monday meeting.

**Comment by rtakacs** [comment]
@glistening I've uploaded #55 that measures the malloc and JerryScript memory allocations separately.

**Comment by glistening** [comment]
I don't think #55 and #57 covers the request what I talked to @zherczeg last week and this Monday. These feature is high priority that would be good to finalized yesterday as I said. I would like to explain again here.

i) No explanation and no chart for runtime measurement. I asked the daily report page must explain what the number in runtime memory usage means. It is composed of `malloc (heap)`, `jerry heap`, and `stack`.

ii) My request for measuring stack was simple. But #57 is trying to measure more precisely. Could you explain it on #57 by comment? (maybe @bzsolt could explain)

**Comment by zherczeg** [comment]
@glistening I try to contact you through IRC
